version: '3.8'

services:
  kafkacat:
    image: generatekafkaalarms
    environment:
      BROKERS: '10.144.36.181:9092,10.144.36.132:9092,10.144.36.125:9092'
      TOPIC: 'event-alert-for-psim_from_mysql'
      DEFAULT_TASK_NAMES: 'SURVEILLANCE'
      DEFAULT_SITE_NAMES: 'Mubadala Tower,Abu Dhabi Mall,Al Reem Mall,Yas Island Mall,Al Wadha Mall,Yas Marina Circuit'
      DEFAULT_DEVICE_IDS: '635140f4cc30cd00093a43be'