services:
  generatekafkaalarms:
    image: registry.obvious.tech/obvious/ooda/connectors/generate-kafka-messages:v1
    environment:
      BROKERS: 10.144.36.181:9092,10.144.36.132:9092,10.144.36.125:9092
      TOPIC: event-alert-for-psim
      DEFAULT_TASK_NAMES: yitu_behavior_event_FIGHT_composition_v1,yitu_behavior_event_CAR_WRONG_WAY_composition_v1,yitu_behavior_event_DOG_composition_v1
      DEFAULT_SITE_NAMES: Mubadala Tower,Abu Dhabi Mall,Al Reem Mall,Yas Island Mall,Al Wadha Mall,Yas Marina Circuit
      DEFAULT_DEVICE_IDS: 635140f4cc30cd00093a43be
      DEFAULT_LOCATIONS: +24.521296+54.675052/,+24.521196+54.675142/
      HIT_FACE_IMAGE_URIs: kv://ytkv-surveillance-image/152/2022/10/26/13/55/8lsr5-584b9b6b-0603-4c8a-b815-23652dca43d4-1666778120735-515127970
      FACE_IMAGE_URIs: kv://ytkv-image-flow-scene/105/2022/10/26/13/58006/8lsr5-584b9b6b-0603-4c8a-b815-23652dca43d4-1666778118071-515127923
      MESSAGES_IN_BURST: 100
      SECONDS_PER_BURST: 5
      DEFAULT_CAMERA_SOURCE_IDS: 10569617014264000
      SCENE_IMAGE_URIs: /image/v1/fusion/storage/eXRrdjEwMTkxOC1mdXNpb24vMDgyLzIwMjIvMTAvMjYvMTcvNTEvaGhycm0tM2YwYmU2YWQtMjQ4MS00MjZlLTkwMzctN2I1ZDQwMGE3M2RhLTE2NjY3Nzc4OTU4MTUtMTk4NTQ5MDk=
      PRE_SCENE_IMAGE_URLs: /image/v1/fusion/storage/eXRrdjEwMTkxOC1mdXNpb24vMDgyLzIwMjIvMTAvMjYvMTcvNTIvaGhycm0tM2YwYmU2YWQtMjQ4MS00MjZlLTkwMzctN2I1ZDQwMGE3M2RhLTE2NjY3Nzc4OTU4MTUtMTk4NTQ5MDk=
      POST_SCENE_IMAGE_URLs: /image/v1/fusion/storage/eXRrdjEwMTkxOC1mdXNpb24vMDgyLzIwMjIvMTAvMjYvMTcvNTMvaGhycm0tM2YwYmU2YWQtMjQ4MS00MjZlLTkwMzctN2I1ZDQwMGE3M2RhLTE2NjY3Nzc4OTU4MTUtMTk4NTQ5MDk=
